[package]
name = "cvlr-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "cvlr_test"

[features]
certora = []
certora-vacuity = ["cvlr/vacuity"]
certora-test = []

[dependencies]
cvlr = { workspace = true }